#!/usr/bin/env python3
"""Generate roadmap PR artifacts from local telemetry."""

from __future__ import annotations

import argparse
from datetime import date
import json
from pathlib import Path
import subprocess
import sys
from typing import Any, Dict, List, Tuple


class RoadmapPrepError(Exception):
    pass


def _run(cmd: List[str], cwd: Path) -> Tuple[int, str, str]:
    try:
        proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=False)
    except Exception as err:
        return 99, "", str(err)
    return int(proc.returncode), proc.stdout or "", proc.stderr or ""


def _load_json(path: Path) -> Dict[str, Any]:
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except Exception as err:
        raise RoadmapPrepError(f"invalid json file {path}: {err}") from err
    if not isinstance(obj, dict):
        raise RoadmapPrepError(f"json file must be object: {path}")
    return obj


def _summary_markdown(rollup: Dict[str, Any]) -> str:
    lines = []
    lines.append(f"# Roadmap Update ({date.today().isoformat()})")
    lines.append("")
    lines.append("## Top Priority Skills")
    for i, skill in enumerate(rollup.get("roadmap_priority", [])[:10], start=1):
        lines.append(f"{i}. {skill}")
    lines.append("")
    lines.append("## Skills Snapshot")
    for row in rollup.get("skills", [])[:20]:
        if not isinstance(row, dict):
            continue
        lines.append(
            f"- {row.get('skill')}: success_rate={row.get('success_rate')} invocations={row.get('invocations')} avg_ms={row.get('avg_duration_ms')}"
        )
    lines.append("")
    return "\n".join(lines) + "\n"


def _pr_body(report: Dict[str, Any], rollup_path: Path, summary_path: Path, repo_root: Path) -> str:
    top = report.get("top_priority", [])
    if not isinstance(top, list):
        top = []
    try:
        rel_rollup = rollup_path.relative_to(repo_root)
    except ValueError:
        rel_rollup = rollup_path
    try:
        rel_summary = summary_path.relative_to(repo_root)
    except ValueError:
        rel_summary = summary_path

    lines = []
    lines.append("<!-- roadmap-pr-prep:daily-roadmap -->")
    lines.append("## Daily Roadmap Update")
    lines.append("")
    lines.append(f"Artifacts:")
    lines.append(f"- `{rel_rollup}`")
    lines.append(f"- `{rel_summary}`")
    lines.append("")
    lines.append("Top priority skills:")
    for i, skill in enumerate(top[:10], start=1):
        lines.append(f"{i}. {skill}")
    lines.append("")
    lines.append("Generated by `roadmap-pr-prep` with deterministic branch + body.")
    lines.append("")
    return "\n".join(lines)


def _open_or_update_pr(
    repo_root: Path,
    branch: str,
    base_branch: str,
    title: str,
    body: str,
    commit_message: str,
    paths: List[Path],
    dry_run: bool,
    skip_pr_if_no_change: bool,
) -> Dict[str, Any]:
    rc, out, err = _run(["git", "rev-parse", "--is-inside-work-tree"], cwd=repo_root)
    if rc != 0 or out.strip() != "true":
        raise RoadmapPrepError("repo_root is not a git repository")

    rc, out, err = _run(["git", "checkout", "-B", branch], cwd=repo_root)
    if rc != 0:
        raise RoadmapPrepError(f"git checkout failed: {err or out}")

    add_cmd = ["git", "add", "--"] + [str(p) for p in paths]
    rc, out, err = _run(add_cmd, cwd=repo_root)
    if rc != 0:
        raise RoadmapPrepError(f"git add failed: {err or out}")

    rc, staged, err = _run(["git", "diff", "--cached", "--name-only"], cwd=repo_root)
    if rc != 0:
        raise RoadmapPrepError(f"git diff --cached failed: {err or staged}")
    has_changes = bool(staged.strip())
    if not has_changes and skip_pr_if_no_change:
        return {
            "mode": "skipped_no_changes",
            "number": 0,
            "url": "",
            "has_changes": False,
            "dry_run": dry_run,
        }

    rc, out, err = _run(["gh", "--version"], cwd=repo_root)
    if rc != 0:
        raise RoadmapPrepError(f"gh CLI unavailable: {err or out}")

    if has_changes and not dry_run:
        rc, out, err = _run(["git", "commit", "-m", commit_message], cwd=repo_root)
        if rc != 0:
            raise RoadmapPrepError(f"git commit failed: {err or out}")

    if not dry_run:
        rc, out, err = _run(["git", "push", "-u", "origin", branch], cwd=repo_root)
        if rc != 0:
            raise RoadmapPrepError(f"git push failed: {err or out}")

    rc, out, err = _run(
        ["gh", "pr", "list", "--state", "open", "--head", branch, "--base", base_branch, "--json", "number,url,title"],
        cwd=repo_root,
    )
    if rc != 0:
        raise RoadmapPrepError(f"gh pr list failed: {err or out}")
    try:
        prs = json.loads(out) if out.strip() else []
    except Exception as parse_err:
        raise RoadmapPrepError(f"invalid gh pr list output: {parse_err}") from parse_err
    if not isinstance(prs, list):
        prs = []

    if prs:
        pr = prs[0] if isinstance(prs[0], dict) else {}
        pr_number = pr.get("number")
        if pr_number is None:
            raise RoadmapPrepError("gh pr list returned invalid number")
        if not dry_run:
            rc, out, err = _run(
                ["gh", "pr", "edit", str(pr_number), "--title", title, "--body", body, "--base", base_branch],
                cwd=repo_root,
            )
            if rc != 0:
                raise RoadmapPrepError(f"gh pr edit failed: {err or out}")
        return {
            "mode": "updated",
            "number": int(pr_number),
            "url": str(pr.get("url", "")),
            "has_changes": has_changes,
            "dry_run": dry_run,
        }

    if dry_run:
        return {
            "mode": "create_pending",
            "number": 0,
            "url": "",
            "has_changes": has_changes,
            "dry_run": True,
        }

    rc, out, err = _run(
        ["gh", "pr", "create", "--head", branch, "--base", base_branch, "--title", title, "--body", body],
        cwd=repo_root,
    )
    if rc != 0:
        raise RoadmapPrepError(f"gh pr create failed: {err or out}")
    pr_url = out.strip().splitlines()[-1] if out.strip() else ""
    return {
        "mode": "created",
        "number": 0,
        "url": pr_url,
        "has_changes": has_changes,
        "dry_run": False,
    }


def run(
    repo_root: Path,
    output_dir: Path,
    open_pr: bool,
    base_branch: str,
    branch_prefix: str,
    dry_run: bool,
    skip_pr_if_no_change: bool,
) -> Dict[str, Any]:
    releases = repo_root / "data" / "skill_releases.jsonl"
    events = repo_root / "data" / "skill_usage_events.jsonl"
    if not releases.exists():
        fallback_releases = repo_root / "skill-adoption-analytics" / "tests" / "fixtures" / "rollup_releases.jsonl"
        if fallback_releases.exists():
            releases = fallback_releases
    schema = repo_root / "skill-adoption-analytics" / "references" / "roadmap_rollup.schema.json"
    rollup_script = repo_root / "skill-adoption-analytics" / "scripts" / "generate_daily_rollup.py"

    if not releases.exists():
        raise RoadmapPrepError(f"missing releases file: {releases}")
    if not events.exists():
        raise RoadmapPrepError(f"missing events file: {events}")

    output_dir.mkdir(parents=True, exist_ok=True)
    stamp = date.today().isoformat()
    rollup_out = output_dir / f"roadmap_rollup_{stamp}.json"
    md_out = output_dir / f"roadmap_summary_{stamp}.md"

    cmd = [
        "python3",
        str(rollup_script),
        "--releases",
        str(releases),
        "--events",
        str(events),
        "--schema",
        str(schema),
        "--output",
        str(rollup_out),
    ]
    rc, out, err = _run(cmd, cwd=repo_root)
    if rc != 0:
        raise RoadmapPrepError(f"rollup generation failed: {err or out}")

    rollup = _load_json(rollup_out)
    md_out.write_text(_summary_markdown(rollup), encoding="utf-8")

    report: Dict[str, Any] = {
        "schema_version": 1,
        "rollup_path": str(rollup_out),
        "summary_md_path": str(md_out),
        "top_priority": list(rollup.get("roadmap_priority", []))[:10],
        "open_pr": {
            "requested": bool(open_pr),
            "mode": "skipped",
            "url": "",
            "branch": "",
            "base": base_branch,
            "dry_run": bool(dry_run),
        },
    }

    if open_pr:
        if not branch_prefix.startswith("codex/"):
            raise RoadmapPrepError("branch-prefix must start with codex/")
        try:
            rollup_out.relative_to(repo_root)
            md_out.relative_to(repo_root)
        except ValueError as err:
            raise RoadmapPrepError("--open-pr requires output-dir within repo-root") from err
        branch = f"{branch_prefix}-{stamp}"
        title = f"roadmap: daily update {stamp}"
        body = _pr_body(report, rollup_path=rollup_out, summary_path=md_out, repo_root=repo_root)
        pr_info = _open_or_update_pr(
            repo_root=repo_root,
            branch=branch,
            base_branch=base_branch,
            title=title,
            body=body,
            commit_message=f"roadmap: daily update {stamp}",
            paths=[rollup_out, md_out],
            dry_run=dry_run,
            skip_pr_if_no_change=skip_pr_if_no_change,
        )
        report["open_pr"] = {
            "requested": True,
            "mode": pr_info.get("mode", "unknown"),
            "url": pr_info.get("url", ""),
            "branch": branch,
            "base": base_branch,
            "dry_run": bool(dry_run),
            "has_changes": bool(pr_info.get("has_changes", False)),
        }

    return report


def parse_args(argv: List[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Prepare roadmap PR artifacts")
    p.add_argument("--repo-root", required=True, help="Path to repo root")
    p.add_argument("--output-dir", default="", help="Optional output dir (default: data/roadmap)")
    p.add_argument("--open-pr", action="store_true", help="Create or update deterministic daily roadmap PR with gh")
    p.add_argument("--base-branch", default="main", help="Base branch for PR")
    p.add_argument("--branch-prefix", default="codex/roadmap-daily", help="Deterministic branch prefix")
    p.add_argument("--skip-pr-if-no-change", action="store_true", help="Skip PR create/update when roadmap artifacts have no staged changes")
    p.add_argument("--dry-run", action="store_true", help="Do not commit/push/create PR; only report planned PR actions")
    p.add_argument("--json", action="store_true", help="Emit JSON")
    return p.parse_args(argv)


def main(argv: List[str]) -> int:
    args = parse_args(argv)
    repo_root = Path(args.repo_root).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve() if args.output_dir else repo_root / "data" / "roadmap"

    try:
        report = run(
            repo_root,
            output_dir,
            open_pr=bool(args.open_pr),
            base_branch=str(args.base_branch),
            branch_prefix=str(args.branch_prefix),
            dry_run=bool(args.dry_run),
            skip_pr_if_no_change=bool(args.skip_pr_if_no_change),
        )
    except RoadmapPrepError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"rollup_path: {report['rollup_path']}")
        print(f"summary_md_path: {report['summary_md_path']}")
        print(f"open_pr_mode: {report['open_pr']['mode']}")
        print(f"open_pr_url: {report['open_pr']['url']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
